Output ../gifs/ReadDemo.gif

Set Width 1200
Set Height 600
Set FontSize 30

Hide
Sleep 0.5s
Show

Type 'Using ctread to read a book using the registry:'
Ctrl+C
Type 'ctread read "The Adventures of Sherlock Holmes"'
Sleep 1s
Enter
Sleep 1s
Type 'Using ctread to read a book using the path:'
Ctrl+C
Type 'ctread read ~/Desktop/go/TestBook.epub'
Sleep 1s
Enter
Sleep 1s
Type 'Using ctread to read a specific chapter of the book:'
Ctrl+C
Type 'ctread read "The Adventures of Sherlock Holmes" 4'
Sleep 1s
Enter
Sleep 1s
