Output ../gifs/RegistryDemo.gif

Set Width 1200
Set Height 600
Set FontSize 30

Hide
Sleep 0.5s
Show

Type 'Adding a entry to the registry:'
Ctrl+C
Type 'ctread registry add /Users/seb/Desktop/go/TestBook.epub'
Sleep 1s
Enter
Sleep 1s
Type 'Deleting a entry from the registry using the name:'
Ctrl+C
Type 'ctread registry delete "Crime and Punishment"'
Sleep 1s
Enter
Sleep 1s
Type 'Listing the items in the registry:'
Ctrl+C
Type 'ctread registry'
Sleep 1s
Enter
Sleep 1s
Type 'clearing the registry:'
Ctrl+C
Type 'ctread registry clear'
Sleep 1s
Enter
Sleep 1s
